services:

  mysql:
    image: mysql:8.4
    container_name: bevatel_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: bevatel_callcenter
      MYSQL_USER: bevatel
      MYSQL_PASSWORD: bevatel_secret

    ports:
      - "3306:3306"

    volumes:
      - bevatel_mysql_data:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.4-alpine
    container_name: bevatel_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - bevatel_redis_data:/data

volumes:
  bevatel_mysql_data:
  bevatel_redis_data: